name: iOS Build and Sign

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Fastlane
      run: gem install fastlane

    - name: Decode and Install Certificate
      run: |
        echo "$DISTRIBUTION_P12" | base64 --decode > certificate.p12
        security create-keychain -p "" build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "" build.keychain
        security import certificate.p12 -k build.keychain -P "$P12_PASSWORD" -T /usr/bin/codesign
        security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain

      env:
        DISTRIBUTION_P12: ${{ secrets.DISTRIBUTION_P12 }}
        P12_PASSWORD: ${{ secrets.P12_PASSWORD }}

    - name: Decode and Install Provisioning Profile
      run: |
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        echo "$PROVISIONING_PROFILE" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision

      env:
        PROVISIONING_PROFILE: ${{ secrets.PROVISIONING_PROFILE }}

    - name: Build and Archive
      run: |
        xcodebuild -workspace dictionaryApp.xcworkspace \
                   -scheme dictionaryApp \
                   -sdk iphoneos \
                   -configuration Release \
                   CODE_SIGN_STYLE=Manual \
                   CODE_SIGN_IDENTITY="Apple Distribution: Ivan Dovhosheia (KZNP8PH94C)" \
                   PROVISIONING_PROFILE_SPECIFIER="wellbe_dictionaryApp_AppStore" \
                   archive -archivePath $GITHUB_WORKSPACE/build/dictionaryApp.xcarchive

    - name: Export IPA
      run: |
        xcodebuild -exportArchive \
                   -archivePath $GITHUB_WORKSPACE/build/dictionaryApp.xcarchive \
                   -exportOptionsPlist exportOptions.plist \
                   -exportPath $GITHUB_WORKSPACE/build

    - name: Upload IPA as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: dictionaryApp
        path: $GITHUB_WORKSPACE/build/dictionaryApp.ipa
